import { Be_Vietnam_Pro } from "next/font/google";
import "./globals.css";

const beVietnamPro = Be_Vietnam_Pro({ subsets: ["latin"], weight: '200' });

export const metadata = {
  title: "Github Profiles",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-primary-bg ${beVietnamPro.className}`}>{children}</body>
    </html>
  );
}
